name: "dnerf-lego"

trainer:
  output_path: "/NASdata/clz/log/gf_tes"
  max_steps: 10000
  val_interval: 5000
  training: True
  enable_gui: True

  spatial_lr_scale: True

  model:
    name: GaussianFlow
    lambda_ssim: 0.2
    point_cloud:
      point_cloud_type: "GaussianFlowPointCloud"  
      unwarp_prefix: "point_cloud"
      max_sh_degree: 3
      pos_traj_dim: 2
      rot_traj_dim: 1
      feat_traj_dim: 2
      rescale_value: 0.5
      offset_value: 0.1
      trainable: true
      random_noise: False
      max_steps: ${trainer.max_steps}
      initializer:
        num_points: 10000
        radius: 1.3
        init_type: 'random'
        feat_dim: 3
    camera_model:
      name: TimeCameraModel
      enable_training: False
    renderer:
      name: "GaussianFlowRender"
      render_depth: False
      max_sh_degree: ${trainer.model.point_cloud.max_sh_degree}
  
  controller:
    name: GFDensificationController
    normalize_grad: False
    control_module: "point_cloud"
    split_num: 2
    prune_interval: 100
    min_opacity: 0.001
    percent_dense: 0.01
    densify_grad_threshold: 0.00005
    duplicate_interval: 100
    densify_start_iter: 500
    densify_stop_iter: 5000
    opacity_reset_interval: 3000
    optimizer_name: "optimizer_1"

  
  gui:
    name: GaussianFlowGUI
    viewer_port: 9012


  optimizer:
    optimizer_1:
      type: BaseOptimizer
      name: Adam
      args:
        eps: 1e-15
      extra_cfg:
        backward: False
      params:
        point_cloud.position:
          lr: 0.00016
        point_cloud.pos_params:
          lr: 0.002
        point_cloud.features:
          lr: 0.0025
        point_cloud.features_rest:
          lr: 0.000125 # features/20
        point_cloud.feat_params:
          lr: 0.0025
        point_cloud.scaling:
          lr: 0.005
        point_cloud.rotation:
          lr: 0.001
        point_cloud.rot_params:
          lr: 0.005
        point_cloud.opacity:
          lr: 0.05
        point_cloud.time_center:
          # lr: 0.001
          lr: 0.0
  scheduler:
    name: "ExponLRScheduler"
    params:
      point_cloud.position:
        init:  0.00016
        final: 0.0000016
        max_steps: ${trainer.max_steps}
      point_cloud.pos_params:
        init:  0.002
        final: 0.0002
        max_steps: ${trainer.max_steps}
  
  datapipeline:
    data_set: "DNeRFDataset"
    shuffle: True
    batch_size: 1
    num_workers: 0
    dataset:
      data_path: "/NASdata/clz/data/d-nerf/data/lego"
      cached_observed_data: True
      scale: 1.0
      white_bg: True

  writer:
    writer_type: "TensorboardWriter"
  
  hooks:
    LogHook:
      name: LogHook
    CheckPointHook:
      name: CheckPointHook
  
  exporter:
    exporter_1:
      type: MetricExporter