name: "garden"

trainer:
  output_path: "/data/datasets/garden_output"
  max_steps: 30000
  val_interval: 5000
  training: True
  enable_gui: True

  model:
    name: BaseModel
    lambda_ssim: 0.2
    point_cloud:
      point_cloud_type: "GaussianPointCloud"  
      max_sh_degree: 3
      trainable: true
      unwarp_prefix: "point_cloud"
      initializer:
        init_type: 'colmap'
        feat_dim: 3
    camera_model:
      name: "CameraModel"
      enable_training: False
    renderer:
      name: "MsplatRender"
      render_depth: True
      max_sh_degree: ${trainer.model.point_cloud.max_sh_degree}

  gui:
    name: BaseGUI
    viewer_port: 8925
  
  controller:
    name: DensificationController
    normalize_grad: False
    control_module: "point_cloud"
    split_num: 2
    prune_interval: 100
    min_opacity: 0.005
    percent_dense: 0.01
    densify_grad_threshold: 0.0002
    duplicate_interval: 100
    densify_start_iter: 500
    densify_stop_iter: 15000
    opacity_reset_interval: 3000
    optimizer_name: "optimizer_1"

  optimizer:
    optimizer_1:
      type: BaseOptimizer
      name: Adam
      args:
        eps: 1e-15
      extra_cfg:
        backward: False
      params:
        point_cloud.position:
          lr: 0.00016
        point_cloud.features:
          lr: 0.0025
        point_cloud.features_rest:
          lr: 0.000125 # features/20
        point_cloud.scaling:
          lr: 0.005
        point_cloud.rotation:
          lr: 0.001
        point_cloud.opacity:
          lr: 0.05
      # camera_params:
      #   lr: 1e-3

  scheduler:
    name: "ExponLRScheduler"
    params:
      point_cloud.position:
        init:  0.00016
        final: 0.0000016
        max_steps: ${trainer.max_steps}
  
  datapipeline:
    data_set: "ColmapDataset"
    shuffle: True
    batch_size: 1
    num_workers: 0
    dataset:
      data_path: "/data/datasets/360_v2/garden"
      cached_observed_data: True
      scale: 0.25
      white_bg: False

  writer:
    writer_type: "TensorboardWriter"
  
  hooks:
    LogHook:
      name: LogHook
    CheckPointHook:
      name: CheckPointHook
  
  exporter:
    exporter_1:
      type: MetricExporter
    exporter_3:
      type: VideoExporter